LoongArch: Mark {dmw,tlb}_virt_to_page() exports as non-GPL
Mainline: 19d86a496233731882aea7ec24505ce6641b1c0c
From: v6.7-rc3
Severity: Moderate

task: 192231

[ Upstream commit 19d86a496233731882aea7ec24505ce6641b1c0c ]

Mark {dmw,tlb}_virt_to_page() exports as non-GPL, in order to let
out-of-tree modules (e.g. OpenZFS) be built without errors. Otherwise
we get:

ERROR: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'dmw_virt_to_page'
ERROR: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'tlb_virt_to_page'

Reported-by: Haowu Ge <gehaowu@bitmoe.com>
Signed-off-by: Huacai Chen <chenhuacai@loongson.cn>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit c28fec461df3869355c95b6baed3c36aa870f1fe)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Idd2128d51587ae082e7f12b8093b7a73449f480d
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/89855
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>