powerpc: Only define __parse_fpscr() when required
Mainline: c7e0d9bb9154c6e6b2ac8746faba27b53393f25e
From: v6.7-rc1
Severity: Low

[ Upstream commit c7e0d9bb9154c6e6b2ac8746faba27b53393f25e ]

Clang 17 reports:

arch/powerpc/kernel/traps.c:1167:19: error: unused function '__parse_fpscr' [-Werror,-Wunused-function]

__parse_fpscr() is called from two sites. First call is guarded
by #ifdef CONFIG_PPC_FPU_REGS

Second call is guarded by CONFIG_MATH_EMULATION which selects
CONFIG_PPC_FPU_REGS.

So only define __parse_fpscr() when CONFIG_PPC_FPU_REGS is defined.

Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202309210327.WkqSd5Bq-lkp@intel.com/
Fixes: b6254ced4da6 ("powerpc/signal: Don't manage floating point regs when no FPU")
Signed-off-by: Christophe Leroy <christophe.leroy@csgroup.eu>
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://msgid.link/5de2998c57f3983563b27b39228ea9a7229d4110.1695385984.git.christophe.leroy@csgroup.eu
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 8d5e9875aeb2b168a1e097d9be07148e75476ec9)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I6793ab507029f1a9850088238cb99d9c95ffe57b
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/83957
Tested-by: k2ci <kernel-bot@kylinos.cn>