clk: qcom: config IPQ_APSS_6018 should depend on QCOM_SMEM
Mainline: 6a15647d0adc686226045e8046369f34d6ab03ed
From: v6.7-rc1
Severity: Low

[ Upstream commit 6a15647d0adc686226045e8046369f34d6ab03ed ]

The config IPQ_APSS_6018 should depend on QCOM_SMEM, to
avoid the following error reported by 'kernel test robot'

	loongarch64-linux-ld: drivers/clk/qcom/apss-ipq6018.o: in function `apss_ipq6018_probe':
	>> apss-ipq6018.c:(.text+0xd0): undefined reference to `qcom_smem_get_soc_id'

Fixes: 5e77b4ef1b19 ("clk: qcom: Add ipq6018 apss clock controller")
Reported-by: kernel test robot <yujie.liu@intel.com>
Closes: https://lore.kernel.org/r/202310181650.g8THtfsm-lkp@intel.com/
Signed-off-by: Varadarajan Narayanan <quic_varada@quicinc.com>
Link: https://lore.kernel.org/r/f4c4d65a7cb71e807d6d472c63c7718408c8f5f0.1697781921.git.quic_varada@quicinc.com
Signed-off-by: Bjorn Andersson <andersson@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 3f4bcf359a90bdb331ad6266523c1d76190e461b)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: Ibdafd178e259bdad8ed6dd177d0869fbe9a5f881
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/83691
Tested-by: k2ci <kernel-bot@kylinos.cn>