PM: tools: Fix sleepgraph syntax error
Mainline: b85e2dab33ce467e8dcf1cb6c0c587132ff17f56
From: v6.7-rc3
Severity: Moderate

task: 188294

[ Upstream commit b85e2dab33ce467e8dcf1cb6c0c587132ff17f56 ]

The sleepgraph tool currently fails:

  File "/usr/bin/sleepgraph", line 4155
    or re.match('psci: CPU(?P<cpu>[0-9]*) killed.*', msg)):
                                                         ^
SyntaxError: unmatched ')'

Fixes: 34ea427e01ea ("PM: tools: sleepgraph: Recognize "CPU killed" messages")
Signed-off-by: David Woodhouse <dwmw@amazon.co.uk>
Reviewed-by: Wolfram Sang <wsa@kernel.org>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 49036a88865eabfb9b05b6920a86f7726441f2c7)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ic57dc500b975c4ff566964e7f4bb98286dafd3bf
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/87351
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>