drm/bridge: tc358768: select CONFIG_VIDEOMODE_HELPERS
Mainline: 26513300978f7285c3e776c144f27ef71be61f57
From: v6.7-rc5
Severity: Moderate

task: 189525

[ Upstream commit 26513300978f7285c3e776c144f27ef71be61f57 ]

A dependency on this feature was recently introduced:

x86_64-linux-ld: vmlinux.o: in function `tc358768_bridge_pre_enable':
tc358768.c:(.text+0xbe3dae): undefined reference to `drm_display_mode_to_videomode'

Make sure this is always enabled.

Fixes: e5fb21678136 ("drm/bridge: tc358768: Use struct videomode")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Neil Armstrong <neil.armstrong@linaro.org>
Link: https://lore.kernel.org/r/20231204072814.968816-1-arnd@kernel.org
Signed-off-by: Neil Armstrong <neil.armstrong@linaro.org>
Link: https://patchwork.freedesktop.org/patch/msgid/20231204072814.968816-1-arnd@kernel.org
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 584bdbca913ed4e6b580f5cf7527bf5b9a731746)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Id3dba3e0b56ffba9415d0f1c824df876a2b9845d
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/88420
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>