debugfs: Fix __rcu type comparison warning
Mainline: 7360a48bd0f5e62b2d00c387d5d3f2821eb290ce
From: v6.7-rc1
Severity: Low

[ Upstream commit 7360a48bd0f5e62b2d00c387d5d3f2821eb290ce ]

Sparse reports the following:

fs/debugfs/file.c:942:9: sparse: sparse: incompatible types in comparison expression (different address spaces):
fs/debugfs/file.c:942:9: sparse:    char [noderef] __rcu *
fs/debugfs/file.c:942:9: sparse:    char *

rcu_assign_pointer() expects that it's assigning to pointers annotated
with __rcu. We can't annotate the generic struct file::private_data, so
cast it instead.

Fixes: 86b5488121db ("debugfs: Add write support to debugfs_create_str()")
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202309091933.BRWlSnCq-lkp@intel.com/
Signed-off-by: Mike Tipton <quic_mdtipton@quicinc.com>
Link: https://lore.kernel.org/r/20230922134512.5126-1-quic_mdtipton@quicinc.com
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 406d424454880087761dab65f7a7591a6e4cb717)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: I099305582f12cb0a4f9869312686476446d07447
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/83940
Tested-by: k2ci <kernel-bot@kylinos.cn>