netfilter: nf_tables: bogus ENOENT when destroying element which does not exist
Mainline: a7d5a955bfa854ac6b0c53aaf933394b4e6139e4
From: v6.7-rc2
Severity: Moderate

task: 186574

[ Upstream commit a7d5a955bfa854ac6b0c53aaf933394b4e6139e4 ]

destroy element command bogusly reports ENOENT in case a set element
does not exist. ENOENT errors are skipped, however, err is still set
and propagated to userspace.

 # nft destroy element ip raw BLACKLIST { 1.2.3.4 }
 Error: Could not process rule: No such file or directory
 destroy element ip raw BLACKLIST { 1.2.3.4 }
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Fixes: f80a612dd77c ("netfilter: nf_tables: add support to destroy operation")
Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit f603b616bafe242efd597dfaef42b22ae6ade0ce)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: I33a892941a947550e708f9cf5458db854fdc6611
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/85511
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>