selftests/net: unix: fix unused variable compiler warning
Mainline: 59fef379d453781f0dabfa1f1a1e86e78aee919a
From: v6.7-rc4
Severity: Moderate

task: 188294

[ Upstream commit 59fef379d453781f0dabfa1f1a1e86e78aee919a ]

Remove an unused variable.

    diag_uid.c:151:24:
    error: unused variable 'udr'
    [-Werror,-Wunused-variable]

Fixes: ac011361bd4f ("af_unix: Add test for sock_diag and UDIAG_SHOW_UID.")
Signed-off-by: Willem de Bruijn <willemb@google.com>
Link: https://lore.kernel.org/r/20231124171645.1011043-4-willemdebruijn.kernel@gmail.com
Signed-off-by: Jakub Kicinski <kuba@kernel.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit a989f76f2218bf751664f7866bb30c754fc17393)

K2CI-Arch: None
Signed-off-by: k2ci <kernel-bot@kylinos.cn>
Change-Id: Ie8cbc541a2ef2baa7a3725fa14de9033ce01cf11
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/87530
Reviewed-by: Jackie Liu <liuyun01@kylinos.cn>