fbdev: fsl-diu-fb: mark wr_reg_wa() static
Mainline: a5035c81847430dfa3482807b07325f29e9e8c09
From: v6.7-rc1
Severity: Low

[ Upstream commit a5035c81847430dfa3482807b07325f29e9e8c09 ]

wr_reg_wa() is not an appropriate name for a global function, and doesn't need
to be global anyway, so mark it static and avoid the warning:

drivers/video/fbdev/fsl-diu-fb.c:493:6: error: no previous prototype for 'wr_reg_wa' [-Werror=missing-prototypes]

Fixes: 0d9dab39fbbe ("powerpc/5121: fsl-diu-fb: fix issue with re-enabling DIU area descriptor")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Helge Deller <deller@gmx.de>
Signed-off-by: Sasha Levin <sashal@kernel.org>

(backported from commit 172056918ad888caac780d494f62fedcfe5a668b)

Signed-off-by: Jackie Liu <liuyun01@kylinos.cn>
Change-Id: Ibabe8d09e5c788466d2f25e4d26ce343fc4ac309
Reviewed-on: http://gerrit.kylin.com/c/klinux/+/84091
Tested-by: k2ci <kernel-bot@kylinos.cn>